# Site settings
title: Katy
email: kdecorah@albany.edu
description: Katy is a front-end developer from New York.
url: http://katystudent.github.io
github_username: katystudent

# Build settings
markdown: kramdown
permalink: pretty
